name: quiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  uuid: ^3.0.7
  # path_provider: ^2.0.0
  # share_plus: ^4.0.0
  pdf: ^3.10.7
  # open_file: ^3.3.2
  # printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
